package main.kasir;

import main.*;
import javax.swing.JOptionPane;

/**
 *
 * @author fawzanpriatmana
 */
public class viewMenuKasir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewMenuKasir.class.getName());

    /**
     * Creates new form viewMenuAdmin
     */
    public viewMenuKasir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuMaster = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemBarang = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemInformasi = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        itemAppKasirJual = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemLaporanPenjualan = new javax.swing.JMenuItem();
        itemLaporanPembelian = new javax.swing.JMenuItem();

        menuMaster.setText("Master");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Halaman Utama [Kasir]");

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel2.setText("TOKO NAWIR");

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 2, 18)); // NOI18N
        jLabel3.setText("Halaman Utama");

        jLabel4.setText("v 1.0");

        menuFile.setText("File");

        itemBarang.setText("Barang");
        itemBarang.addActionListener(this::itemBarangActionPerformed);
        menuFile.add(itemBarang);
        menuFile.add(jSeparator1);

        itemInformasi.setText("Informasi");
        itemInformasi.addActionListener(this::itemInformasiActionPerformed);
        menuFile.add(itemInformasi);

        itemLogout.setText("Log Out");
        itemLogout.addActionListener(this::itemLogoutActionPerformed);
        menuFile.add(itemLogout);

        itemExit.setText("Exit");
        itemExit.addActionListener(this::itemExitActionPerformed);
        menuFile.add(itemExit);

        jMenuBar1.add(menuFile);

        menuTransaksi.setText("Transaksi");

        itemAppKasirJual.setText("Prog. Kasir (Untuk Jual)");
        itemAppKasirJual.addActionListener(this::itemAppKasirJualActionPerformed);
        menuTransaksi.add(itemAppKasirJual);
        menuTransaksi.add(jSeparator2);

        itemLaporanPenjualan.setText("Transaksi Penjualan");
        itemLaporanPenjualan.addActionListener(this::itemLaporanPenjualanActionPerformed);
        menuTransaksi.add(itemLaporanPenjualan);

        itemLaporanPembelian.setText("Transaksi Pembelian");
        itemLaporanPembelian.addActionListener(this::itemLaporanPembelianActionPerformed);
        menuTransaksi.add(itemLaporanPembelian);

        jMenuBar1.add(menuTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(553, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(337, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        int confirmKeluar = JOptionPane.showConfirmDialog(
                this,
                "Apakah mau keluar dari aplikasi?",
                "Keluar?",
                JOptionPane.YES_NO_OPTION
        );
        
        if (confirmKeluar == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformasiActionPerformed
        viewInformasi tampilInformasi = new viewInformasi();
        tampilInformasi.setVisible(true);
    }//GEN-LAST:event_itemInformasiActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        int confirmLogout = JOptionPane.showConfirmDialog(
                this, "Apakah ingin log out?",
                "Log Out?",
                JOptionPane.YES_NO_OPTION);
        
        if (confirmLogout == 0) {
            viewLogin tampilLogin = new viewLogin();
            tampilLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void itemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarangActionPerformed
        viewBarangKasir tampilBarang = new viewBarangKasir();
        tampilBarang.setVisible(true);
    }//GEN-LAST:event_itemBarangActionPerformed

    private void itemAppKasirJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAppKasirJualActionPerformed
        viewAppKasirJual tampilAppKasirJual = new viewAppKasirJual();
        tampilAppKasirJual.setVisible(true);
    }//GEN-LAST:event_itemAppKasirJualActionPerformed

    private void itemLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLaporanPenjualanActionPerformed
        viewLaporanPenjualanKasir tampilLaporanJual = new viewLaporanPenjualanKasir();
        tampilLaporanJual.setVisible(true);
    }//GEN-LAST:event_itemLaporanPenjualanActionPerformed

    private void itemLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLaporanPembelianActionPerformed
        viewLaporanPembelianKasir tampilLaporanBeli = new viewLaporanPembelianKasir();
        tampilLaporanBeli.setVisible(true);
    }//GEN-LAST:event_itemLaporanPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewMenuKasir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAppKasirJual;
    private javax.swing.JMenuItem itemBarang;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemInformasi;
    private javax.swing.JMenuItem itemLaporanPembelian;
    private javax.swing.JMenuItem itemLaporanPenjualan;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
