package main.admin;

import config.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fawzanpriatmana
 */
public class viewKategoriAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewKategoriAdmin.class.getName());

    /**
     * Creates new form viewBarang
     */
    public viewKategoriAdmin() {
        initComponents();
        dataTabelKategori();
        this.setLocationRelativeTo(null);
    }
    
    private void clearComponents() {
        kotakIdKategori.setText(null);
        kotakNamaKategori.setText(null);
        comboStatus.setSelectedIndex(0);
        kotakIdKategori.setEnabled(true);
        kotakNamaKategori.requestFocusInWindow();
    }
    
    private void dataTabelKategori() {
        
        DefaultTableModel tabelKategori = new DefaultTableModel();
        tabelKategori.addColumn("ID Kategori");
        tabelKategori.addColumn("Nama Kategori");
        tabelKategori.addColumn("Status");
        this.tabelKategori.setModel(tabelKategori);
        
        try {
            Koneksi koneksiTampilTabel = new Koneksi();
            String sql = "SELECT * FROM kategori";
            Statement stmt = koneksiTampilTabel.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                tabelKategori.addRow(new Object[] {
                    rs.getString("id_kategori"),
                    rs.getString("nama_kategori"),
                    rs.getString("status")
                });
            }
            
        } catch (Exception e) {
            e.getStackTrace();
        }
        
    }
    
    private void autoIdKategori() {
        try {
            Koneksi koneksiAutoIdUser = new Koneksi();
            String sql = "SELECT id_kategori FROM kategori ORDER BY id_kategori DESC LIMIT 1";

            Statement st = koneksiAutoIdUser.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String id_user = rs.getString("id_kategori");
                int nomor = Integer.parseInt(id_user.substring(3));
                nomor++;

                String no_urut = String.format("KTG%03d", nomor);
                kotakIdKategori.setText(no_urut);
            } else {
                kotakIdKategori.setText("KTG001");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal generate ID User!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tombolSimpan = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        kotakIdKategori = new javax.swing.JTextField();
        kotakNamaKategori = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        tombolBaru = new javax.swing.JButton();
        tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKategori = new javax.swing.JTable();
        tombolRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daftar Kategori [Admin]");
        setAlwaysOnTop(true);

        title.setPreferredSize(new java.awt.Dimension(400, 133));

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel2.setText("TOKO NAWIR");

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 2, 18)); // NOI18N
        jLabel1.setText("Kategori");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("ID Kategori");

        jLabel4.setText("Nama Kategori");

        jLabel9.setText("Status");

        tombolSimpan.setText("Tambah");
        tombolSimpan.addActionListener(this::tombolSimpanActionPerformed);

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(this::tombolUbahActionPerformed);

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(this::tombolHapusActionPerformed);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Aktif", "Tidak Aktif" }));

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(this::tombolBaruActionPerformed);

        javax.swing.GroupLayout formBarangLayout = new javax.swing.GroupLayout(formBarang);
        formBarang.setLayout(formBarangLayout);
        formBarangLayout.setHorizontalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolBaru)
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(tombolSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolHapus))
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakIdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        formBarangLayout.setVerticalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotakIdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kotakNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpan)
                    .addComponent(tombolUbah)
                    .addComponent(tombolHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolBaru)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabelKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Kategori", "Status"
            }
        ));
        tabelKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKategori);

        tombolRefresh.setText("Refresh Table");
        tombolRefresh.addActionListener(this::tombolRefreshActionPerformed);

        javax.swing.GroupLayout tabelLayout = new javax.swing.GroupLayout(tabel);
        tabel.setLayout(tabelLayout);
        tabelLayout.setHorizontalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombolRefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tabelLayout.setVerticalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tombolRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed

        String idKategori = kotakIdKategori.getText();
        String namaKategori = kotakNamaKategori.getText();
        String statusKategori = comboStatus.getSelectedItem().toString();

        if (statusKategori.equals("-- Pilih --")) {
            System.out.println("Silahkan pilih statusnya (Aktif/Tidak Aktif)");
            return;
        }
        
        try {
            Koneksi koneksiKategoriSimpan = new Koneksi();
            String sqlInsert = "INSERT INTO kategori VALUES "
                    + "(?, ?, ?)";
            PreparedStatement pstmt = koneksiKategoriSimpan.prepareStatement(sqlInsert);
            pstmt.setString(1, idKategori);
            pstmt.setString(2, namaKategori);
            pstmt.setString(3, statusKategori);
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Berhasil menyimpan kategori "
                    + namaKategori +" ("
                    +idKategori+")");
            System.out.println("ID Kategori: " + idKategori);
            System.out.println("Nama Kategori: " + namaKategori);
            System.out.println("Status: " + statusKategori);
            System.out.println();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelKategori();
        clearComponents();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        clearComponents();
        autoIdKategori();
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tabelKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKategoriMouseClicked
        int i = tabelKategori.getSelectedRow();
        
        String tempTableIdKategori = (String) tabelKategori.getValueAt(i, 0);
        String tempTableNamaKategori = (String) tabelKategori.getValueAt(i, 1);
        String tempTableStatusKategori = (String) tabelKategori.getValueAt(i, 2);
        
        kotakIdKategori.setText(tempTableIdKategori);
        kotakNamaKategori.setText(tempTableNamaKategori);
        
        if (tempTableStatusKategori.equals("aktif")) {
            comboStatus.setSelectedIndex(1);
        } else if (tempTableStatusKategori.equals("tidak aktif")) {
            comboStatus.setSelectedIndex(2);
        }

        kotakIdKategori.setEnabled(false);
    }//GEN-LAST:event_tabelKategoriMouseClicked

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        String idKategori = kotakIdKategori.getText();
        String namaKategori = kotakNamaKategori.getText();
        
        try {
            Koneksi koneksiUserHapus = new Koneksi();

            String sqlInsert = "DELETE FROM kategori WHERE "
                    + "id_kategori = ?";

            PreparedStatement pstmt = koneksiUserHapus.prepareStatement(sqlInsert);
            pstmt.setString(1, idKategori);

            int confirmDelete = JOptionPane.showConfirmDialog(this,
                    "Apakah ingin menghapus user dengan nama "
                    + namaKategori + " (" + idKategori + ")?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmDelete == 0) {
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Berhasil menghapus " + namaKategori + " ("
                        + idKategori + ")");
                System.out.println("Hapus user dengan id (" + idKategori + ")");
                System.out.println();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelKategori();
        clearComponents();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRefreshActionPerformed
        dataTabelKategori();
    }//GEN-LAST:event_tombolRefreshActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        
        String idKategori = kotakIdKategori.getText();
        String namaKategori = kotakNamaKategori.getText();
        String statusKategori = comboStatus.getSelectedItem().toString();

        if (statusKategori.equals("-- Pilih --")) {
            System.out.println("Silahkan pilih statusnya (Aktif/Tidak Aktif)");
            return;
        }

        try {
            Koneksi koneksiKategoriSimpan = new Koneksi();
            String sqlInsert = "UPDATE kategori SET "
                    + "nama_kategori = ?, "
                    + "status = ? "
                    + "WHERE id_kategori = ?";
            PreparedStatement pstmt = koneksiKategoriSimpan.prepareStatement(sqlInsert);
            pstmt.setString(1, namaKategori);
            pstmt.setString(2, statusKategori);
            pstmt.setString(3, idKategori);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Berhasil update kategori "
                    + namaKategori + " ("
                    + idKategori + ")");
            System.out.println("ID Kategori: " + idKategori);
            System.out.println("Nama Kategori: " + namaKategori);
            System.out.println("Status: " + statusKategori);
            System.out.println();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelKategori();
        clearComponents();
    }//GEN-LAST:event_tombolUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewKategoriAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JPanel formBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kotakIdKategori;
    private javax.swing.JTextField kotakNamaKategori;
    private javax.swing.JPanel tabel;
    private javax.swing.JTable tabelKategori;
    private javax.swing.JPanel title;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolRefresh;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
}
