package main.admin;

import config.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fawzanpriatmana
 */
public class viewUserAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewUserAdmin.class.getName());

    /**
     * Creates new form viewBarang
     */
    public viewUserAdmin() {
        initComponents();
        dataTabelUser();
        this.setLocationRelativeTo(null);
    }

    private void clearComponents() {
        kotakIdUser.setText(null);
        kotakNamaUser.setText(null);
        kotakUsername.setText(null);
        kotakPassword.setText(null);
        comboRole.setSelectedIndex(0);
        comboStatus.setSelectedIndex(0);
        kotakIdUser.setEnabled(true);
        kotakPassword.setEnabled(true);
        kotakNamaUser.requestFocusInWindow();
    }
    
    private void dataTabelUser() {
        
        DefaultTableModel tabelUser = new DefaultTableModel();
        tabelUser.addColumn("ID");
        tabelUser.addColumn("Nama");
        tabelUser.addColumn("Username");
        tabelUser.addColumn("Role");
        tabelUser.addColumn("Status");
        this.tabelUser.setModel(tabelUser);
        
        try {
            Koneksi koneksiTampilTabel = new Koneksi();
            
            String sql = "SELECT * FROM users";

            Statement stm = koneksiTampilTabel.createStatement();
            ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                tabelUser.addRow(new Object[]{
                    rs.getString("id_user"),
                    rs.getString("nama"),
                    rs.getString("username"),
                    rs.getString("role"),
                    rs.getString("status")});
            }
        } catch (SQLException e) {
            e.getStackTrace();
        }
        
    }
    
    private void autoIdUser() {
        try {
            Koneksi koneksiAutoIdUser = new Koneksi();
            String sql = "SELECT id_user FROM users ORDER BY id_user DESC LIMIT 1";

            Statement stmt = koneksiAutoIdUser.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            if (rs.next()) {
                String id_user = rs.getString("id_user");
                int nomor = Integer.parseInt(id_user.substring(3));
                nomor++;
                
                String no_urut = String.format("USR%04d", nomor);
                kotakIdUser.setText(no_urut);
            } else {
                kotakIdUser.setText("USR0001");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal generate ID User!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tombolSimpan = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        kotakIdUser = new javax.swing.JTextField();
        kotakNamaUser = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        tombolBaru = new javax.swing.JButton();
        kotakUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        kotakPassword = new javax.swing.JPasswordField();
        tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        tombolRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daftar User [Admin]");
        setAlwaysOnTop(true);

        title.setPreferredSize(new java.awt.Dimension(400, 133));

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel2.setText("TOKO NAWIR");

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 2, 18)); // NOI18N
        jLabel1.setText("User");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("ID User");

        jLabel4.setText("Nama User");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel9.setText("Role");

        tombolSimpan.setText("Tambah");
        tombolSimpan.addActionListener(this::tombolSimpanActionPerformed);

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(this::tombolUbahActionPerformed);

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(this::tombolHapusActionPerformed);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Aktif", "Tidak Aktif" }));

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(this::tombolBaruActionPerformed);

        jLabel10.setText("Status");

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Pemilik", "Kasir" }));

        javax.swing.GroupLayout formBarangLayout = new javax.swing.GroupLayout(formBarang);
        formBarang.setLayout(formBarangLayout);
        formBarangLayout.setHorizontalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolBaru)
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(tombolSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolHapus))
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(41, 41, 41)
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kotakNamaUser, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(kotakUsername)
                            .addComponent(kotakPassword)
                            .addComponent(kotakIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                .addComponent(comboRole, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formBarangLayout.setVerticalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotakIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kotakNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kotakUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kotakPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpan)
                    .addComponent(tombolUbah)
                    .addComponent(tombolHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolBaru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Username", "Role", "Status"
            }
        ));
        tabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelUser);
        if (tabelUser.getColumnModel().getColumnCount() > 0) {
            tabelUser.getColumnModel().getColumn(0).setMinWidth(50);
            tabelUser.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelUser.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        tombolRefresh.setText("Refresh Table");
        tombolRefresh.addActionListener(this::tombolRefreshActionPerformed);

        javax.swing.GroupLayout tabelLayout = new javax.swing.GroupLayout(tabel);
        tabel.setLayout(tabelLayout);
        tabelLayout.setHorizontalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombolRefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tabelLayout.setVerticalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tombolRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        
        String idUser = kotakIdUser.getText();
        String namaUser = kotakNamaUser.getText();
        String username = kotakUsername.getText();
        char[] passwordChar = kotakPassword.getPassword();
        String roleUser = comboRole.getSelectedItem().toString();
        String statusUser = comboStatus.getSelectedItem().toString();
        
        if (idUser.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan buat user terlebih dahulu!\n(ID User Kosong)",
                    "Pilih User",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if (namaUser.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nama User tidak boleh kosong!",
                    "Nama User Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Username tidak boleh kosong!",
                    "Username Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (roleUser.equals("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih role",
                    "Pilih Role",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if (statusUser.equals("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih statusnya (Aktif/Tidak Aktif)",
                    "Pilih Status",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            Koneksi koneksiUserSimpan = new Koneksi();

            String sqlInsert = "INSERT INTO users VALUES"
                    + "(?, ?, ?, md5(?), ?, ?)";
            
            PreparedStatement pstmt = koneksiUserSimpan.prepareStatement(sqlInsert);
            pstmt.setString(1, idUser);
            pstmt.setString(2, namaUser);
            pstmt.setString(3, username);
            pstmt.setString(4, new String (passwordChar));
            pstmt.setString(5, roleUser);
            pstmt.setString(6, statusUser);
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Berhasil menyimpan "+namaUser+" ("
                    +username+")");
                System.out.println("ID User: "+idUser);
                System.out.println("Nama User: " + namaUser);
                System.out.println("Username: "+username);
                System.out.println("Password: "+passwordChar);
                System.out.println("Role: "+roleUser);
                System.out.println("Status: "+statusUser);
                System.out.println();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelUser();
        clearComponents();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUserMouseClicked
        int i = tabelUser.getSelectedRow();
        
        String tempTableIdUser = (String) tabelUser.getValueAt(i, 0);
        String tempTableNamaUser = (String) tabelUser.getValueAt(i, 1);
        String tempTableUsername = (String) tabelUser.getValueAt(i, 2);
        String tempTableRoleUser = (String) tabelUser.getValueAt(i, 3);
        String tempTableStatusUser = (String) tabelUser.getValueAt(i, 4);
        
        kotakIdUser.setText(tempTableIdUser);
        kotakNamaUser.setText(tempTableNamaUser);
        kotakUsername.setText(tempTableUsername);
        
        if (tempTableRoleUser.equals("pemilik")) {
            comboRole.setSelectedIndex(1);
        } else if (tempTableRoleUser.equals("kasir")) {
            comboRole.setSelectedIndex(2);
        }
        
        if (tempTableStatusUser.equals("aktif")) {
            comboStatus.setSelectedIndex(1);
        } else if (tempTableStatusUser.equals("tidak aktif")) {
            comboStatus.setSelectedIndex(2);
        }
        kotakIdUser.setEnabled(false);
        kotakPassword.setEnabled(false);
    }//GEN-LAST:event_tabelUserMouseClicked

    private void tombolRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRefreshActionPerformed
        dataTabelUser();
    }//GEN-LAST:event_tombolRefreshActionPerformed

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        clearComponents();
        autoIdUser();
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        String idUser = kotakIdUser.getText();
        String namaUser = kotakNamaUser.getText();
        String username = kotakUsername.getText();
        
        if (idUser.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih user terlebih dahulu!\n(ID User Kosong)",
                    "Pilih User",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            Koneksi koneksiUserHapus = new Koneksi();

            String sqlDelete = "DELETE FROM users WHERE "
                    + "id_user = ?";
            
            PreparedStatement pstmt = koneksiUserHapus.prepareStatement(sqlDelete);
            pstmt.setString(1, idUser);
            
            int confirmDelete = JOptionPane.showConfirmDialog(this,
                    "Apakah ingin menghapus user dengan nama "
                            + namaUser +" ("+username+")?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );
            
            if (confirmDelete == 0) {
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Berhasil menghapus " + namaUser + " ("
                        + username + ")");
                System.out.println("Hapus user dengan id (" + idUser + ")");
                System.out.println();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelUser();
        clearComponents();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        
        String idUser = kotakIdUser.getText();
        String namaUser = kotakNamaUser.getText();
        String username = kotakUsername.getText();
        String roleUser = comboRole.getSelectedItem().toString();
        String statusUser = comboStatus.getSelectedItem().toString();

        if (idUser.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih user terlebih dahulu!\n(ID User Kosong)",
                    "Pilih User",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (namaUser.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nama User tidak boleh kosong!",
                    "Nama User Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Username tidak boleh kosong!",
                    "Username Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (roleUser.contains("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih role",
                    "Pilih Role",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (statusUser.contains("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih statusnya (Aktif/Tidak Aktif)",
                    "Pilih Status",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            Koneksi koneksiUserUpdate = new Koneksi();

            String sqlUpdate = "UPDATE users SET "
                    + "nama = ?, "
                    + "username = ?, "
                    + "role = ?, "
                    + "status = ? "
                    + "WHERE id_user = ?";

            PreparedStatement pstmt = koneksiUserUpdate.prepareStatement(sqlUpdate);
            pstmt.setString(1, namaUser);
            pstmt.setString(2, username);
            pstmt.setString(3, roleUser);
            pstmt.setString(4, statusUser);
            pstmt.setString(5, idUser);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Berhasil update " + namaUser + " ("
                    + username + ")");
            System.out.println("ID User: " + idUser);
            System.out.println("Nama User: " + namaUser);
            System.out.println("Username: " + username);
            System.out.println("Role: " + roleUser);
            System.out.println("Status: " + statusUser);
            System.out.println();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelUser();
        clearComponents();
    }//GEN-LAST:event_tombolUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewUserAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JPanel formBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kotakIdUser;
    private javax.swing.JTextField kotakNamaUser;
    private javax.swing.JPasswordField kotakPassword;
    private javax.swing.JTextField kotakUsername;
    private javax.swing.JPanel tabel;
    private javax.swing.JTable tabelUser;
    private javax.swing.JPanel title;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolRefresh;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
}
