package main.admin;

import config.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fawzanpriatmana
 */
public class viewSupplierAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewSupplierAdmin.class.getName());

    /**
     * Creates new form viewBarang
     */
    public viewSupplierAdmin() {
        initComponents();
        dataTabelSupplier();
        this.setLocationRelativeTo(null);
    }
    
    private void clearComponents() {
        kotakIdSupplier.setText(null);
        kotakNamaSupplier.setText(null);
        kotakAlamat.setText(null);
        kotakTelepon.setText(null);
        comboStatus.setSelectedIndex(0);
        kotakIdSupplier.setEnabled(true);
        kotakNamaSupplier.requestFocusInWindow();
    }

    private void dataTabelSupplier() {

        DefaultTableModel tabelSupplier = new DefaultTableModel();
        tabelSupplier.addColumn("ID");
        tabelSupplier.addColumn("Nama Supplier");
        tabelSupplier.addColumn("Alamat");
        tabelSupplier.addColumn("Telepon");
        tabelSupplier.addColumn("Status");
        this.tabelSupplier.setModel(tabelSupplier);

        try {
            Koneksi koneksiTampilTabel = new Koneksi();

            String sql = "SELECT * FROM supplier";

            Statement stm = koneksiTampilTabel.createStatement();
            ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                tabelSupplier.addRow(new Object[]{
                    rs.getString("id_supplier"),
                    rs.getString("nama_suppl"),
                    rs.getString("alamat"),
                    rs.getString("telepon"),
                    rs.getString("status")
                });
            }
        } catch (SQLException e) {
            e.getStackTrace();
        }

    }
    
    private void autoIdSupplier() {
        try {
            Koneksi koneksiAutoIdSupplier = new Koneksi();
            String sql = "SELECT id_supplier FROM supplier "
                    + "ORDER BY id_supplier DESC LIMIT 1";

            Statement st = koneksiAutoIdSupplier.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String id_user = rs.getString("id_supplier");
                int nomor = Integer.parseInt(id_user.substring(3));
                nomor++;

                String no_urut = String.format("SUP%04d", nomor);
                kotakIdSupplier.setText(no_urut);
            } else {
                kotakIdSupplier.setText("SUP0001");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal generate ID User!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tombolSimpan = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        kotakIdSupplier = new javax.swing.JTextField();
        kotakNamaSupplier = new javax.swing.JTextField();
        kotakTelepon = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        tombolBaru = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kotakAlamat = new javax.swing.JTextArea();
        tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSupplier = new javax.swing.JTable();
        tombolRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daftar Supplier [Admin]");
        setAlwaysOnTop(true);

        title.setPreferredSize(new java.awt.Dimension(400, 133));

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel2.setText("TOKO NAWIR");

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 2, 18)); // NOI18N
        jLabel1.setText("Supplier");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("ID Supplier");

        jLabel4.setText("Nama Supplier");

        jLabel5.setText("Alamat Supplier");

        jLabel6.setText("Telepon");

        jLabel9.setText("Status");

        tombolSimpan.setText("Tambah");
        tombolSimpan.addActionListener(this::tombolSimpanActionPerformed);

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(this::tombolUbahActionPerformed);

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(this::tombolHapusActionPerformed);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Aktif", "Tidak Aktif" }));

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(this::tombolBaruActionPerformed);

        kotakAlamat.setColumns(20);
        kotakAlamat.setRows(5);
        jScrollPane2.setViewportView(kotakAlamat);

        javax.swing.GroupLayout formBarangLayout = new javax.swing.GroupLayout(formBarang);
        formBarang.setLayout(formBarangLayout);
        formBarangLayout.setHorizontalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolBaru)
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(tombolSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolHapus))
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formBarangLayout.setVerticalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotakIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kotakNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kotakTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpan)
                    .addComponent(tombolUbah)
                    .addComponent(tombolHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolBaru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabel.setPreferredSize(new java.awt.Dimension(498, 567));

        tabelSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Supploer", "Alamat", "Telepon", "Status"
            }
        ));
        tabelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSupplier);

        tombolRefresh.setText("Refresh Table");
        tombolRefresh.addActionListener(this::tombolRefreshActionPerformed);

        javax.swing.GroupLayout tabelLayout = new javax.swing.GroupLayout(tabel);
        tabel.setLayout(tabelLayout);
        tabelLayout.setHorizontalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombolRefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tabelLayout.setVerticalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tombolRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        String idSupplier = kotakIdSupplier.getText();
        String namaSupplier = kotakNamaSupplier.getText();
        String alamatSupplier = kotakAlamat.getText();
        String teleponSupplier = kotakTelepon.getText();
        String statusSupplier = comboStatus.getSelectedItem().toString();

        if (statusSupplier.equals("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih statusnya (Aktif/Tidak Aktif)",
                    "Pilih Status",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            Koneksi koneksiSupplierSimpan = new Koneksi();
            String sqlInsert = "INSERT INTO supplier VALUES "
                    + "(?, ?, ?, ?, ?)";
            PreparedStatement pstmt = koneksiSupplierSimpan.prepareStatement(sqlInsert);
            pstmt.setString(1, idSupplier);
            pstmt.setString(2, namaSupplier);
            pstmt.setString(3, alamatSupplier);
            pstmt.setString(4, teleponSupplier);
            pstmt.setString(5, statusSupplier);
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Berhasil menyimpan " + namaSupplier + " ("
                    + idSupplier + ")");
            System.out.println("ID Supplier: " + idSupplier);
            System.out.println("Nama Supplier: " + namaSupplier);
            System.out.println("Alamat: " + alamatSupplier);
            System.out.println("Telepon: " + teleponSupplier);
            System.out.println("Status: " + statusSupplier);
            System.out.println();            

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelSupplier();
        clearComponents();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tabelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSupplierMouseClicked
        int i = tabelSupplier.getSelectedRow();
        
        String tempTableIdSupplier = (String) tabelSupplier.getValueAt(i, 0);
        String tempTableNamaSupplier = (String) tabelSupplier.getValueAt(i, 1);
        String tempTableAlamatSupplier = (String) tabelSupplier.getValueAt(i, 2);
        String tempTableTeleponSupplier = (String) tabelSupplier.getValueAt(i, 3);
        String tempTableStatusSupplier = (String) tabelSupplier.getValueAt(i, 4);
        
        kotakIdSupplier.setText(tempTableIdSupplier);
        kotakNamaSupplier.setText(tempTableNamaSupplier);
        kotakAlamat.setText(tempTableAlamatSupplier);
        kotakTelepon.setText(tempTableTeleponSupplier);
        if (tempTableStatusSupplier.equals("aktif")) {
            comboStatus.setSelectedIndex(1);
        } else if (tempTableStatusSupplier.equals("tidak aktif")) {
            comboStatus.setSelectedIndex(2);
        }
        kotakIdSupplier.setEnabled(false);
    }//GEN-LAST:event_tabelSupplierMouseClicked

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        clearComponents();
        autoIdSupplier();
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tombolRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRefreshActionPerformed
        dataTabelSupplier();
    }//GEN-LAST:event_tombolRefreshActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        String idSupplier = kotakIdSupplier.getText();
        String namaSupplier = kotakNamaSupplier.getText();

        try {
            Koneksi koneksiSupplierHapus = new Koneksi();
            String sqlInsert = "DELETE FROM supplier "
                    + "WHERE id_supplier = ?";
            PreparedStatement pstmt = koneksiSupplierHapus.prepareStatement(sqlInsert);
            pstmt.setString(1, idSupplier);
            pstmt.executeUpdate();
            
            int confirmDelete = JOptionPane.showConfirmDialog(this,
                    "Apakah ingin menghapus supplier dengan nama "
                    + namaSupplier + " (" + idSupplier + ")?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmDelete == 0) {
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Berhasil menghapus " + namaSupplier + " ("
                        + idSupplier + ")");
                System.out.println("Hapus supplier dengan id (" + idSupplier + ")");
                System.out.println();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelSupplier();
        clearComponents();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        String idSupplier = kotakIdSupplier.getText();
        String namaSupplier = kotakNamaSupplier.getText();
        String alamatSupplier = kotakAlamat.getText();
        String teleponSupplier = kotakTelepon.getText();
        String statusSupplier = comboStatus.getSelectedItem().toString();

        if (statusSupplier.equals("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih statusnya (Aktif/Tidak Aktif)",
                    "Pilih Status",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            Koneksi koneksiSupplierSimpan = new Koneksi();
            String sqlInsert = "UPDATE supplier SET "
                    + "nama_suppl = ?, "
                    + "alamat = ?, "
                    + "telepon = ?, "
                    + "status = ? "
                    + "WHERE id_supplier = ?";
            PreparedStatement pstmt = koneksiSupplierSimpan.prepareStatement(sqlInsert);
            pstmt.setString(1, namaSupplier);
            pstmt.setString(2, alamatSupplier);
            pstmt.setString(3, teleponSupplier);
            pstmt.setString(4, statusSupplier);
            pstmt.setString(5, idSupplier);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Berhasil update " + namaSupplier + " ("
                    + idSupplier + ")");
            System.out.println("ID Supplier: " + idSupplier);
            System.out.println("Nama Supplier: " + namaSupplier);
            System.out.println("Alamat: " + alamatSupplier);
            System.out.println("Telepon: " + teleponSupplier);
            System.out.println("Status: " + statusSupplier);
            System.out.println();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelSupplier();
        clearComponents();
    }//GEN-LAST:event_tombolUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewSupplierAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JPanel formBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea kotakAlamat;
    private javax.swing.JTextField kotakIdSupplier;
    private javax.swing.JTextField kotakNamaSupplier;
    private javax.swing.JTextField kotakTelepon;
    private javax.swing.JPanel tabel;
    private javax.swing.JTable tabelSupplier;
    private javax.swing.JPanel title;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolRefresh;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
}
