package main.admin;

import config.Koneksi;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fawzanpriatmana
 */
public class viewBarangAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewBarangAdmin.class.getName());

    /**
     * Creates new form viewBarang
     */
    public viewBarangAdmin() {
        initComponents();
        tampilKategori();
        dataTabelBarang();
        this.setLocationRelativeTo(null);
    }

    private void clearComponents() {
        kotakIdBarang.setText(null);
        kotakNamaBarang.setText(null);
        comboKategori.setSelectedIndex(0);
        kotakIdBarang.setEnabled(true);
        kotakNamaBarang.requestFocusInWindow();
    }

    private void tampilKategori() {
        DefaultComboBoxModel comboKategori = new DefaultComboBoxModel();
        comboKategori.addElement("-- Pilih --");

        try {
            Koneksi koneksiTampilKategori = new Koneksi();
            String sqlKategori = "SELECT nama_kategori FROM kategori "
                    + "WHERE status = 'aktif'";

            Statement stmt = koneksiTampilKategori.createStatement();
            ResultSet rs = stmt.executeQuery(sqlKategori);

            while (rs.next()) {
                comboKategori.addElement(
                        rs.getString("nama_kategori")
                );
                this.comboKategori.setModel(comboKategori);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void dataTabelBarang() {

        DefaultTableModel tabelBarang = new DefaultTableModel();
        tabelBarang.addColumn("ID Barang");
        tabelBarang.addColumn("Nama Barang");
        tabelBarang.addColumn("Kategori Barang");
        this.tabelBarang.setModel(tabelBarang);

        try {
            Koneksi koneksiTampilTabel = new Koneksi();

            String sql = "SELECT id_barang, nama_brg, nama_kategori "
                    + "FROM barang INNER JOIN kategori "
                    + "ON barang.id_kategori = kategori.id_kategori "
                    + "ORDER BY id_barang ASC";

            Statement stm = koneksiTampilTabel.createStatement();
            ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                tabelBarang.addRow(new Object[]{
                    rs.getString("id_barang"),
                    rs.getString("nama_brg"),
                    rs.getString("nama_kategori")});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void autoIdBarang() {
        try {
            Koneksi koneksiAutoIdBarang = new Koneksi();
            String sql = "SELECT id_barang FROM barang ORDER BY id_barang DESC LIMIT 1";

            Statement st = koneksiAutoIdBarang.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String id_user = rs.getString("id_barang");
                int nomor = Integer.parseInt(id_user.substring(3));
                nomor++;

                String no_urut = String.format("BRG%04d", nomor);
                kotakIdBarang.setText(no_urut);
            } else {
                kotakIdBarang.setText("BRG0001");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal generate ID Barang!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tombolSimpan = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        kotakIdBarang = new javax.swing.JTextField();
        kotakNamaBarang = new javax.swing.JTextField();
        comboKategori = new javax.swing.JComboBox<>();
        tombolBaru = new javax.swing.JButton();
        tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        tombolRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daftar Barang [Admin]");
        setAlwaysOnTop(true);

        title.setPreferredSize(new java.awt.Dimension(400, 133));

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel2.setText("TOKO NAWIR");

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 2, 18)); // NOI18N
        jLabel1.setText("Barang");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("ID Barang");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Kategori Barang");

        tombolSimpan.setText("Tambah");
        tombolSimpan.addActionListener(this::tombolSimpanActionPerformed);

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(this::tombolUbahActionPerformed);

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(this::tombolHapusActionPerformed);

        comboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(this::tombolBaruActionPerformed);

        javax.swing.GroupLayout formBarangLayout = new javax.swing.GroupLayout(formBarang);
        formBarang.setLayout(formBarangLayout);
        formBarangLayout.setHorizontalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolBaru)
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(tombolSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolHapus))
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotakIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        formBarangLayout.setVerticalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotakIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kotakNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpan)
                    .addComponent(tombolUbah)
                    .addComponent(tombolHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolBaru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Kategori Barang"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        tombolRefresh.setText("Refresh Table");
        tombolRefresh.addActionListener(this::tombolRefreshActionPerformed);

        javax.swing.GroupLayout tabelLayout = new javax.swing.GroupLayout(tabel);
        tabel.setLayout(tabelLayout);
        tabelLayout.setHorizontalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombolRefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        tabelLayout.setVerticalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tombolRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed

        String idBarang = kotakIdBarang.getText();
        String namaBarang = kotakNamaBarang.getText();
        String kategoriBarangDipilih = comboKategori.getSelectedItem().toString();
        
        if (idBarang.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID Barang Kosong",
                    "ID Barang Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if (namaBarang.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nama barang kosong",
                    "Nama Barang Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (kategoriBarangDipilih.equals("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih kategori",
                    "Pilih kategori",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            Koneksi koneksiBarangSimpan = new Koneksi();
            String idKategori = "";

            String sqlAmbilKategori = "SELECT id_kategori FROM kategori "
                    + "WHERE nama_kategori = ?";
            PreparedStatement pstmtAmbilKategori
                    = koneksiBarangSimpan.prepareStatement(sqlAmbilKategori);
            pstmtAmbilKategori.setString(1, kategoriBarangDipilih);
            ResultSet rsAmbilKategori = pstmtAmbilKategori.executeQuery();

            if (rsAmbilKategori.next()) {
                idKategori = rsAmbilKategori.getString("id_kategori");
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Kategori tidak ditemukan di database!"
                );
                return;
            }

            String sqlInsert = "INSERT INTO barang VALUES "
                    + "(?, ?, ?)";
            PreparedStatement pstmtInsert
                    = koneksiBarangSimpan.prepareStatement(sqlInsert);
            pstmtInsert.setString(1, idBarang);
            pstmtInsert.setString(2, namaBarang);
            pstmtInsert.setString(3, idKategori);
            pstmtInsert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Berhasil menyimpan " + namaBarang + " ("
                    + idBarang + ")");
            System.out.println("ID Barang: " + idBarang);
            System.out.println("Nama Barang: " + namaBarang);
            System.out.println("ID Kategori: " + idKategori + " (" + kategoriBarangDipilih + ")");
            System.out.println();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelBarang();
        clearComponents();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        clearComponents();
        autoIdBarang();
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tombolRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRefreshActionPerformed
        dataTabelBarang();
    }//GEN-LAST:event_tombolRefreshActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        int i = tabelBarang.getSelectedRow();

        String tempTableIdBarang = tabelBarang.getValueAt(i, 0).toString();
        String tempTableNamaBarang = tabelBarang.getValueAt(i, 1).toString();
        String tempTableKategoriBarang = tabelBarang.getValueAt(i, 2).toString();

        kotakIdBarang.setText(tempTableIdBarang);
        kotakNamaBarang.setText(tempTableNamaBarang);
        comboKategori.setSelectedItem(tempTableKategoriBarang);

        kotakIdBarang.setEnabled(false);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        String idBarang = kotakIdBarang.getText();
        String namaBarang = kotakNamaBarang.getText();
        
        if (idBarang.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID Barang belum dipilih",
                    "ID Barang Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            Koneksi koneksiBarangHapus = new Koneksi();

            String sqlDelete = "DELETE FROM barang WHERE "
                    + "id_barang = ?";

            PreparedStatement pstmt = koneksiBarangHapus.prepareStatement(sqlDelete);
            pstmt.setString(1, idBarang);

            int confirmDelete = JOptionPane.showConfirmDialog(this,
                    "Apakah ingin menghapus barang dengan nama "
                    + namaBarang + " (" + idBarang + ")?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmDelete == 0) {
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Berhasil menghapus " + namaBarang + " ("
                        + idBarang + ")");
                System.out.println("Hapus barang dengan id (" + idBarang + ")");
                System.out.println();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelBarang();
        clearComponents();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        String idBarang = kotakIdBarang.getText();
        String namaBarang = kotakNamaBarang.getText();
        String kategoriBarangDipilih = comboKategori.getSelectedItem().toString();
        
        if (idBarang.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID Barang belum dipilih",
                    "ID Barang Kosong",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (kategoriBarangDipilih.equals("-- Pilih --")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih kategori",
                    "Pilih kategori",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            Koneksi koneksiBarangUpdate = new Koneksi();
            String idKategori = "";

            String sqlAmbilKategori = "SELECT id_kategori FROM kategori "
                    + "WHERE nama_kategori = ?";
            PreparedStatement pstmtAmbilKategori
                    = koneksiBarangUpdate.prepareStatement(sqlAmbilKategori);
            pstmtAmbilKategori.setString(1, kategoriBarangDipilih);
            ResultSet rsAmbilKategori = pstmtAmbilKategori.executeQuery();

            if (rsAmbilKategori.next()) {
                idKategori = rsAmbilKategori.getString("id_kategori");
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Kategori tidak ditemukan di database!"
                );
                return;
            }

            String sqlInsert = "UPDATE barang SET "
                    + "nama_brg = ?, "
                    + "id_kategori = ? "
                    + "WHERE id_barang = ?";
            PreparedStatement pstmtInsert
                    = koneksiBarangUpdate.prepareStatement(sqlInsert);
            pstmtInsert.setString(1, namaBarang);
            pstmtInsert.setString(2, idKategori);
            pstmtInsert.setString(3, idBarang);
            pstmtInsert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Berhasil update " + namaBarang + " ("
                    + idBarang + ")");
            System.out.println("ID Barang: " + idBarang);
            System.out.println("Nama Barang: " + namaBarang);
            System.out.println("ID Kategori: " + idKategori + " (" + kategoriBarangDipilih + ")");
            System.out.println();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
        dataTabelBarang();
        clearComponents();
    }//GEN-LAST:event_tombolUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewBarangAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboKategori;
    private javax.swing.JPanel formBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kotakIdBarang;
    private javax.swing.JTextField kotakNamaBarang;
    private javax.swing.JPanel tabel;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JPanel title;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolRefresh;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
}
