package main;

import main.kasir.viewMenuKasir;
import main.admin.viewMenuAdmin;
import config.Koneksi;
//import java.math.BigInteger;
//import java.security.MessageDigest;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author fawzanpriatmana
 */
public class viewLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewLogin.class.getName());

    /**
     * Creates new form viewLogin
     */
    public viewLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loginForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kotakUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kotakPassword = new javax.swing.JPasswordField();
        tombolLogin = new javax.swing.JButton();
        tombolAksesLangsung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel2.setText("TOKO NAWIR");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(10, 10, 10))
        );

        jLabel1.setText("Username");

        jLabel3.setText("Password");

        tombolLogin.setText("Login");
        tombolLogin.addActionListener(this::tombolLoginActionPerformed);

        tombolAksesLangsung.setText("Instant Akses");
        tombolAksesLangsung.setEnabled(false);
        tombolAksesLangsung.addActionListener(this::tombolAksesLangsungActionPerformed);

        javax.swing.GroupLayout loginFormLayout = new javax.swing.GroupLayout(loginForm);
        loginForm.setLayout(loginFormLayout);
        loginFormLayout.setHorizontalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFormLayout.createSequentialGroup()
                        .addComponent(tombolLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolAksesLangsung))
                    .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(kotakUsername)
                        .addComponent(jLabel3)
                        .addComponent(kotakPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        loginFormLayout.setVerticalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotakUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotakPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolLogin)
                    .addComponent(tombolAksesLangsung))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLoginActionPerformed
//        JOptionPane.showMessageDialog(this, "Masih belum berfungsi ya! :3");
        String username = kotakUsername.getText();
        char[] passwordChar = kotakPassword.getPassword();

        
        if (username.isEmpty() && passwordChar.length == 0) {
            JOptionPane.showMessageDialog(this, "Silakan isi username dan password anda!");
            return;
        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan isi username anda!");
            return;
        } else if (passwordChar.length == 0) {
            JOptionPane.showMessageDialog(this, "Silakan isi password anda!");
            return;
        }
        
        System.out.println("Username: "+username);
        System.out.println("Password: "+passwordChar);
        System.out.println();
        
        try {
            Koneksi koneksiLogin = new Koneksi();
            String sqlCekLogin = "SELECT * FROM users "
                    + "WHERE username = ? "
                    + "AND password = md5(?)";

            PreparedStatement pstmt = koneksiLogin.prepareStatement(sqlCekLogin);
//            Statement stmt = koneksiLogin.createStatement();
            pstmt.setString(1, username);
            pstmt.setString(2, new String (passwordChar));
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.first()) {
                String namaFound = rs.getString("nama");
                String usernameFound = rs.getString("username");
                String passwordFound = rs.getString("password");
                String hakAksesFound = rs.getString("role");
                
                JOptionPane.showMessageDialog(this, "Berhasil login, Halo "+namaFound);
                
                System.out.println("Nama: "+namaFound);
                System.out.println("Username: "+usernameFound);
                System.out.println("Password: "+passwordFound);
                System.out.println("Hak Akses: "+hakAksesFound);
                System.out.println();
                
                if (hakAksesFound.equals("pemilik")) {
                    viewMenuAdmin tampilMenuAdmin = new viewMenuAdmin();
                    tampilMenuAdmin.setVisible(true);
                    this.dispose();
                } else if (hakAksesFound.equals("kasir")) {
                    viewMenuKasir tampilMenuKasir = new viewMenuKasir();
                    tampilMenuKasir.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Userame dan Password Salah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tombolLoginActionPerformed

    private void tombolAksesLangsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolAksesLangsungActionPerformed
        viewMenuAdmin tampilMenuAdmin = new viewMenuAdmin();
        tampilMenuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolAksesLangsungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField kotakPassword;
    private javax.swing.JTextField kotakUsername;
    private javax.swing.JPanel loginForm;
    private javax.swing.JPanel title;
    private javax.swing.JButton tombolAksesLangsung;
    private javax.swing.JButton tombolLogin;
    // End of variables declaration//GEN-END:variables
}
